apiVersion: v2
name: maildev
version: 0.4.0
appVersion: 2.2.1
kubeVersion: ">=1.19.0-0"
type: application
description: SMTP Server + Web Interface for viewing and testing emails during development.
keywords:
- maildev
- smtp
- nodemailer
- smtp-server
- mailcatcher
- testing
- development
- developer-tools
- nodejs
home: https://thomassamson.github.io/helm-maildev/
icon: https://avatars1.githubusercontent.com/u/26743469
sources:
- https://github.com/ThomasSamson/helm-maildev
- https://github.com/maildev/maildev
maintainers:
- name: ThomasSamson
  url: https://github.com/ThomasSamson
- name: pando85
  email: pando85@users.noreply.github.com
